# Generated by Django 4.2.5 on 2023-10-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoInternet',
            fields=[
                ('id_acceso_internet', models.AutoField(primary_key=True, serialize=False)),
                ('acceso_internet', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'acceso_internet',
            },
        ),
        migrations.CreateModel(
            name='ActividadTrabajo',
            fields=[
                ('id_actividad_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_trabajo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'actividad_trabajo',
            },
        ),
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id_centro_salud', models.AutoField(primary_key=True, serialize=False)),
                ('centro_salud', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'centro_salud',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='DetalleAccesoInternet',
            fields=[
                ('id_detalle_acceso_internet', models.AutoField(primary_key=True, serialize=False)),
                ('acceso_internet', models.ForeignKey(db_column='acceso_internet', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.accesointernet')),
            ],
            options={
                'db_table': 'detalle_acceso_internet',
            },
        ),
        migrations.CreateModel(
            name='DetalleCentroSalud',
            fields=[
                ('id_detalle_centro_salud', models.AutoField(primary_key=True, serialize=False)),
                ('centro_salud', models.ForeignKey(db_column='centro_salud', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.centrosalud')),
            ],
            options={
                'db_table': 'detalle_centro_salud',
            },
        ),
        migrations.CreateModel(
            name='DetalleMes',
            fields=[
                ('id_detalle_mes', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_mes',
            },
        ),
        migrations.CreateModel(
            name='DetalleRazonAbandono',
            fields=[
                ('id_detalle_razon_abandono', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_razon_abandono',
            },
        ),
        migrations.CreateModel(
            name='DetalleTurnoTrabajo',
            fields=[
                ('id_detalle_turno_trabajo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detalle_turno_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('foto', models.CharField(blank=True, max_length=255)),
                ('ci', models.CharField(max_length=30, unique=True)),
                ('complemento', models.CharField(blank=True, max_length=10)),
                ('expedido', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.BooleanField(choices=[(True, 'Hombre'), (False, 'Mujer')])),
                ('numero_rude', models.BigIntegerField(unique=True)),
                ('estado_pago', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaInternet',
            fields=[
                ('id_frecuencia_internet', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia_internet', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'frecuencia_internet',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaSalud',
            fields=[
                ('id_frecuencia_salud', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia_salud', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'frecuencia_salud',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaTrabajo',
            fields=[
                ('id_frecuencia_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia_trabajo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'frecuencia_trabajo',
            },
        ),
        migrations.CreateModel(
            name='GradoDiscapacidad',
            fields=[
                ('id_grado_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('grado_discapacidad', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'grado_discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'idioma',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(blank=True, max_length=50)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.departamento')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='MedioTransporte',
            fields=[
                ('id_medio_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('medio_transporte', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'medio_transporte',
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mes', models.CharField(blank=True, max_length=100)),
                ('numero_mes', models.IntegerField()),
            ],
            options={
                'db_table': 'mes',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(blank=True, max_length=50)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.departamento')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='NacionPuebloIndigena',
            fields=[
                ('id_nacion_pueblo_indigena', models.AutoField(primary_key=True, serialize=False)),
                ('nacion_pueblo_indigena', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'nacion_pueblo_indigena',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(blank=True, max_length=50)),
                ('departamento', models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.departamento')),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='RazonAbandono',
            fields=[
                ('id_razon_abandono', models.AutoField(primary_key=True, serialize=False)),
                ('razon_abandono', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'razon_abandono',
            },
        ),
        migrations.CreateModel(
            name='RelacionFamiliar',
            fields=[
                ('id_relacion_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('relacion_familiar', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'relacion_familiar',
            },
        ),
        migrations.CreateModel(
            name='TiempoTransporte',
            fields=[
                ('id_tiempo_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_transporte', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'tiempo_transporte',
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('id_tipo_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'tipo_discapacidad',
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabajo',
            fields=[
                ('id_turno_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('turno_trabajo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'turno_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('vivienda', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'vivienda',
            },
        ),
        migrations.CreateModel(
            name='RegistroRude',
            fields=[
                ('id_registro_rude', models.AutoField(primary_key=True, serialize=False)),
                ('numero_oficialia', models.IntegerField()),
                ('numero_libro', models.IntegerField()),
                ('numero_partida', models.IntegerField()),
                ('numero_folio', models.IntegerField()),
                ('discapacidad', models.BooleanField()),
                ('numero_registro_discapacidad', models.IntegerField(blank=True, null=True)),
                ('zona_villa', models.CharField(max_length=100)),
                ('avenida_calle', models.CharField(max_length=150)),
                ('numero_vivienda', models.IntegerField()),
                ('telefono_fijo', models.IntegerField()),
                ('celular_contacto', models.IntegerField()),
                ('centro_salud', models.BooleanField()),
                ('seguro_salud', models.BooleanField()),
                ('acceso_agua', models.BooleanField()),
                ('acceso_baño', models.BooleanField()),
                ('acceso_red_alcantarilla', models.BooleanField()),
                ('acceso_energia_electrica', models.BooleanField()),
                ('acceso_servicio_basura', models.BooleanField()),
                ('trabajo', models.BooleanField()),
                ('otro_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('pago', models.BooleanField()),
                ('tipo_pago', models.BooleanField(choices=[(True, 'En dinero'), (False, 'En Especie')])),
                ('otro_medio_transporte', models.CharField(blank=True, max_length=100, null=True)),
                ('abandono_gestion_pasada', models.BooleanField()),
                ('actividad_trabajo', models.ForeignKey(db_column='actividad_trabajo', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.actividadtrabajo')),
                ('detalle_acceso_internet', models.ManyToManyField(through='estudiante_app.DetalleAccesoInternet', to='estudiante_app.accesointernet')),
                ('detalle_centro_salud', models.ManyToManyField(through='estudiante_app.DetalleCentroSalud', to='estudiante_app.centrosalud')),
                ('detalle_mes', models.ManyToManyField(through='estudiante_app.DetalleMes', to='estudiante_app.mes')),
                ('detalle_turno_trabajo', models.ManyToManyField(through='estudiante_app.DetalleTurnoTrabajo', to='estudiante_app.turnotrabajo')),
                ('direccion_departamento', models.ForeignKey(db_column='direccion_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_departamento', to='estudiante_app.departamento')),
                ('direccion_localidad', models.ForeignKey(db_column='direccion_localidad', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_registrorudeloc_set', to='estudiante_app.localidad')),
                ('direccion_municipio', models.ForeignKey(db_column='direccion_municipio', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_registrorudemun_set', to='estudiante_app.municipio')),
                ('direccion_provincia', models.ForeignKey(db_column='direccion_provincia', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_registrorudeprov_set', to='estudiante_app.provincia')),
                ('estudiante', models.ForeignKey(db_column='estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.estudiante')),
                ('frecuencia_internet', models.ForeignKey(db_column='frecuencia_internet', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.frecuenciainternet')),
                ('frecuencia_salud', models.ForeignKey(db_column='frecuencia_salud', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.frecuenciasalud')),
                ('frecuencia_trabajo', models.ForeignKey(db_column='frecuencia_trabajo', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.frecuenciatrabajo')),
                ('grado_discapacidad', models.ForeignKey(blank=True, db_column='grado_discapacidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.gradodiscapacidad')),
                ('idioma_actual', models.ForeignKey(db_column='idioma_actual', on_delete=django.db.models.deletion.CASCADE, related_name='idioma_actual', to='estudiante_app.idioma')),
                ('idioma_niñez', models.ForeignKey(db_column='idioma_niñez', on_delete=django.db.models.deletion.CASCADE, related_name='idioma_niñez', to='estudiante_app.idioma')),
                ('lugar_de_nacimiento_departamento', models.ForeignKey(db_column='lugar_de_nacimiento_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='lugar_de_nacimiento_departamento', to='estudiante_app.departamento')),
                ('lugar_de_nacimiento_localidad', models.ForeignKey(db_column='lugar_de_nacimiento_localidad', on_delete=django.db.models.deletion.CASCADE, related_name='lugar_de_nacimiento_localidad', to='estudiante_app.localidad')),
                ('lugar_de_nacimiento_pais', models.ForeignKey(db_column='lugar_de_nacimiento_pais', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.pais')),
                ('lugar_de_nacimiento_provincia', models.ForeignKey(db_column='lugar_de_nacimiento_provincia', on_delete=django.db.models.deletion.CASCADE, related_name='lugar_de_nacimiento_provincia', to='estudiante_app.provincia')),
                ('medio_transporte', models.ForeignKey(db_column='medio_transporte', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.mediotransporte')),
                ('nacion_pueblo_indigena', models.ForeignKey(db_column='nacion_pueblo_indigena', on_delete=django.db.models.deletion.CASCADE, related_name='nacion_pueblo_indigenaregistro', to='estudiante_app.nacionpuebloindigena')),
                ('razon_abadono', models.ManyToManyField(through='estudiante_app.DetalleRazonAbandono', to='estudiante_app.razonabandono')),
                ('relacion_familiar', models.ForeignKey(db_column='relacion_familiar', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.relacionfamiliar')),
                ('tiempo_transporte', models.ForeignKey(db_column='tiempo_transporte', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.tiempotransporte')),
                ('tipo_discapacidad', models.ForeignKey(blank=True, db_column='tipo_discapacidad', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.tipodiscapacidad')),
                ('vivienda', models.ForeignKey(db_column='vivienda', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.vivienda')),
            ],
            options={
                'db_table': 'registro_rude',
            },
        ),
        migrations.AddField(
            model_name='detalleturnotrabajo',
            name='registro_rude',
            field=models.ForeignKey(db_column='registro_rude', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.registrorude'),
        ),
        migrations.AddField(
            model_name='detalleturnotrabajo',
            name='turno_trabajo',
            field=models.ForeignKey(db_column='turno_trabajo', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.turnotrabajo'),
        ),
        migrations.AddField(
            model_name='detallerazonabandono',
            name='razon_abandono',
            field=models.ForeignKey(db_column='razon_abandono', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.razonabandono'),
        ),
        migrations.AddField(
            model_name='detallerazonabandono',
            name='registro_rude',
            field=models.ForeignKey(db_column='registro_rude', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.registrorude'),
        ),
        migrations.AddField(
            model_name='detallemes',
            name='mes',
            field=models.ForeignKey(db_column='mes', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.mes'),
        ),
        migrations.AddField(
            model_name='detallemes',
            name='registro_rude',
            field=models.ForeignKey(db_column='registro_rude', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.registrorude'),
        ),
        migrations.AddField(
            model_name='detallecentrosalud',
            name='registro_rude',
            field=models.ForeignKey(db_column='registro_rude', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.registrorude'),
        ),
        migrations.AddField(
            model_name='detalleaccesointernet',
            name='registro_rude',
            field=models.ForeignKey(db_column='registro_rude', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.registrorude'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(db_column='pais', on_delete=django.db.models.deletion.CASCADE, to='estudiante_app.pais'),
        ),
    ]
